// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eywacontract/eywacontract/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetRegisterTypeRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetRegisterTypeRequest) Reset()         { *m = QueryGetRegisterTypeRequest{} }
func (m *QueryGetRegisterTypeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRegisterTypeRequest) ProtoMessage()    {}
func (*QueryGetRegisterTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{2}
}
func (m *QueryGetRegisterTypeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRegisterTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRegisterTypeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRegisterTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRegisterTypeRequest.Merge(m, src)
}
func (m *QueryGetRegisterTypeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRegisterTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRegisterTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRegisterTypeRequest proto.InternalMessageInfo

func (m *QueryGetRegisterTypeRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetRegisterTypeResponse struct {
	RegisterType RegisterType `protobuf:"bytes,1,opt,name=registerType,proto3" json:"registerType"`
}

func (m *QueryGetRegisterTypeResponse) Reset()         { *m = QueryGetRegisterTypeResponse{} }
func (m *QueryGetRegisterTypeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRegisterTypeResponse) ProtoMessage()    {}
func (*QueryGetRegisterTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{3}
}
func (m *QueryGetRegisterTypeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRegisterTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRegisterTypeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRegisterTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRegisterTypeResponse.Merge(m, src)
}
func (m *QueryGetRegisterTypeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRegisterTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRegisterTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRegisterTypeResponse proto.InternalMessageInfo

func (m *QueryGetRegisterTypeResponse) GetRegisterType() RegisterType {
	if m != nil {
		return m.RegisterType
	}
	return RegisterType{}
}

type QueryAllRegisterTypeRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRegisterTypeRequest) Reset()         { *m = QueryAllRegisterTypeRequest{} }
func (m *QueryAllRegisterTypeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRegisterTypeRequest) ProtoMessage()    {}
func (*QueryAllRegisterTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{4}
}
func (m *QueryAllRegisterTypeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRegisterTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRegisterTypeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRegisterTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRegisterTypeRequest.Merge(m, src)
}
func (m *QueryAllRegisterTypeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRegisterTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRegisterTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRegisterTypeRequest proto.InternalMessageInfo

func (m *QueryAllRegisterTypeRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllRegisterTypeResponse struct {
	RegisterType []RegisterType      `protobuf:"bytes,1,rep,name=registerType,proto3" json:"registerType"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRegisterTypeResponse) Reset()         { *m = QueryAllRegisterTypeResponse{} }
func (m *QueryAllRegisterTypeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRegisterTypeResponse) ProtoMessage()    {}
func (*QueryAllRegisterTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{5}
}
func (m *QueryAllRegisterTypeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRegisterTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRegisterTypeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRegisterTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRegisterTypeResponse.Merge(m, src)
}
func (m *QueryAllRegisterTypeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRegisterTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRegisterTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRegisterTypeResponse proto.InternalMessageInfo

func (m *QueryAllRegisterTypeResponse) GetRegisterType() []RegisterType {
	if m != nil {
		return m.RegisterType
	}
	return nil
}

func (m *QueryAllRegisterTypeResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetSendChatTypeRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetSendChatTypeRequest) Reset()         { *m = QueryGetSendChatTypeRequest{} }
func (m *QueryGetSendChatTypeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSendChatTypeRequest) ProtoMessage()    {}
func (*QueryGetSendChatTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{6}
}
func (m *QueryGetSendChatTypeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSendChatTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSendChatTypeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSendChatTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSendChatTypeRequest.Merge(m, src)
}
func (m *QueryGetSendChatTypeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSendChatTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSendChatTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSendChatTypeRequest proto.InternalMessageInfo

func (m *QueryGetSendChatTypeRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetSendChatTypeResponse struct {
	SendChatType SendChatType `protobuf:"bytes,1,opt,name=sendChatType,proto3" json:"sendChatType"`
}

func (m *QueryGetSendChatTypeResponse) Reset()         { *m = QueryGetSendChatTypeResponse{} }
func (m *QueryGetSendChatTypeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSendChatTypeResponse) ProtoMessage()    {}
func (*QueryGetSendChatTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{7}
}
func (m *QueryGetSendChatTypeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSendChatTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSendChatTypeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSendChatTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSendChatTypeResponse.Merge(m, src)
}
func (m *QueryGetSendChatTypeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSendChatTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSendChatTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSendChatTypeResponse proto.InternalMessageInfo

func (m *QueryGetSendChatTypeResponse) GetSendChatType() SendChatType {
	if m != nil {
		return m.SendChatType
	}
	return SendChatType{}
}

type QueryAllSendChatTypeRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSendChatTypeRequest) Reset()         { *m = QueryAllSendChatTypeRequest{} }
func (m *QueryAllSendChatTypeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllSendChatTypeRequest) ProtoMessage()    {}
func (*QueryAllSendChatTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{8}
}
func (m *QueryAllSendChatTypeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSendChatTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSendChatTypeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSendChatTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSendChatTypeRequest.Merge(m, src)
}
func (m *QueryAllSendChatTypeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSendChatTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSendChatTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSendChatTypeRequest proto.InternalMessageInfo

func (m *QueryAllSendChatTypeRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllSendChatTypeResponse struct {
	SendChatType []SendChatType      `protobuf:"bytes,1,rep,name=sendChatType,proto3" json:"sendChatType"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSendChatTypeResponse) Reset()         { *m = QueryAllSendChatTypeResponse{} }
func (m *QueryAllSendChatTypeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllSendChatTypeResponse) ProtoMessage()    {}
func (*QueryAllSendChatTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{9}
}
func (m *QueryAllSendChatTypeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSendChatTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSendChatTypeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSendChatTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSendChatTypeResponse.Merge(m, src)
}
func (m *QueryAllSendChatTypeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSendChatTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSendChatTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSendChatTypeResponse proto.InternalMessageInfo

func (m *QueryAllSendChatTypeResponse) GetSendChatType() []SendChatType {
	if m != nil {
		return m.SendChatType
	}
	return nil
}

func (m *QueryAllSendChatTypeResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetHandshakeTypeRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetHandshakeTypeRequest) Reset()         { *m = QueryGetHandshakeTypeRequest{} }
func (m *QueryGetHandshakeTypeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetHandshakeTypeRequest) ProtoMessage()    {}
func (*QueryGetHandshakeTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{10}
}
func (m *QueryGetHandshakeTypeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetHandshakeTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetHandshakeTypeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetHandshakeTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetHandshakeTypeRequest.Merge(m, src)
}
func (m *QueryGetHandshakeTypeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetHandshakeTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetHandshakeTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetHandshakeTypeRequest proto.InternalMessageInfo

func (m *QueryGetHandshakeTypeRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetHandshakeTypeResponse struct {
	HandshakeType HandshakeType `protobuf:"bytes,1,opt,name=handshakeType,proto3" json:"handshakeType"`
}

func (m *QueryGetHandshakeTypeResponse) Reset()         { *m = QueryGetHandshakeTypeResponse{} }
func (m *QueryGetHandshakeTypeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetHandshakeTypeResponse) ProtoMessage()    {}
func (*QueryGetHandshakeTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{11}
}
func (m *QueryGetHandshakeTypeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetHandshakeTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetHandshakeTypeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetHandshakeTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetHandshakeTypeResponse.Merge(m, src)
}
func (m *QueryGetHandshakeTypeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetHandshakeTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetHandshakeTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetHandshakeTypeResponse proto.InternalMessageInfo

func (m *QueryGetHandshakeTypeResponse) GetHandshakeType() HandshakeType {
	if m != nil {
		return m.HandshakeType
	}
	return HandshakeType{}
}

type QueryAllHandshakeTypeRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllHandshakeTypeRequest) Reset()         { *m = QueryAllHandshakeTypeRequest{} }
func (m *QueryAllHandshakeTypeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllHandshakeTypeRequest) ProtoMessage()    {}
func (*QueryAllHandshakeTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{12}
}
func (m *QueryAllHandshakeTypeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllHandshakeTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllHandshakeTypeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllHandshakeTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllHandshakeTypeRequest.Merge(m, src)
}
func (m *QueryAllHandshakeTypeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllHandshakeTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllHandshakeTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllHandshakeTypeRequest proto.InternalMessageInfo

func (m *QueryAllHandshakeTypeRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllHandshakeTypeResponse struct {
	HandshakeType []HandshakeType     `protobuf:"bytes,1,rep,name=handshakeType,proto3" json:"handshakeType"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllHandshakeTypeResponse) Reset()         { *m = QueryAllHandshakeTypeResponse{} }
func (m *QueryAllHandshakeTypeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllHandshakeTypeResponse) ProtoMessage()    {}
func (*QueryAllHandshakeTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90dddaedbed5ef05, []int{13}
}
func (m *QueryAllHandshakeTypeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllHandshakeTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllHandshakeTypeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllHandshakeTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllHandshakeTypeResponse.Merge(m, src)
}
func (m *QueryAllHandshakeTypeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllHandshakeTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllHandshakeTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllHandshakeTypeResponse proto.InternalMessageInfo

func (m *QueryAllHandshakeTypeResponse) GetHandshakeType() []HandshakeType {
	if m != nil {
		return m.HandshakeType
	}
	return nil
}

func (m *QueryAllHandshakeTypeResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "eywacontract.eywacontract.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "eywacontract.eywacontract.QueryParamsResponse")
	proto.RegisterType((*QueryGetRegisterTypeRequest)(nil), "eywacontract.eywacontract.QueryGetRegisterTypeRequest")
	proto.RegisterType((*QueryGetRegisterTypeResponse)(nil), "eywacontract.eywacontract.QueryGetRegisterTypeResponse")
	proto.RegisterType((*QueryAllRegisterTypeRequest)(nil), "eywacontract.eywacontract.QueryAllRegisterTypeRequest")
	proto.RegisterType((*QueryAllRegisterTypeResponse)(nil), "eywacontract.eywacontract.QueryAllRegisterTypeResponse")
	proto.RegisterType((*QueryGetSendChatTypeRequest)(nil), "eywacontract.eywacontract.QueryGetSendChatTypeRequest")
	proto.RegisterType((*QueryGetSendChatTypeResponse)(nil), "eywacontract.eywacontract.QueryGetSendChatTypeResponse")
	proto.RegisterType((*QueryAllSendChatTypeRequest)(nil), "eywacontract.eywacontract.QueryAllSendChatTypeRequest")
	proto.RegisterType((*QueryAllSendChatTypeResponse)(nil), "eywacontract.eywacontract.QueryAllSendChatTypeResponse")
	proto.RegisterType((*QueryGetHandshakeTypeRequest)(nil), "eywacontract.eywacontract.QueryGetHandshakeTypeRequest")
	proto.RegisterType((*QueryGetHandshakeTypeResponse)(nil), "eywacontract.eywacontract.QueryGetHandshakeTypeResponse")
	proto.RegisterType((*QueryAllHandshakeTypeRequest)(nil), "eywacontract.eywacontract.QueryAllHandshakeTypeRequest")
	proto.RegisterType((*QueryAllHandshakeTypeResponse)(nil), "eywacontract.eywacontract.QueryAllHandshakeTypeResponse")
}

func init() {
	proto.RegisterFile("eywacontract/eywacontract/query.proto", fileDescriptor_90dddaedbed5ef05)
}

var fileDescriptor_90dddaedbed5ef05 = []byte{
	// 720 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcf, 0x4f, 0x13, 0x4f,
	0x14, 0xef, 0xc0, 0x17, 0x92, 0xef, 0x08, 0xc1, 0x8c, 0x1c, 0xb4, 0xe2, 0xaa, 0x13, 0x45, 0x44,
	0xd9, 0x4d, 0x0b, 0xf1, 0x57, 0x4c, 0x0c, 0x98, 0x88, 0x47, 0xa8, 0xc4, 0x83, 0x17, 0x32, 0xb4,
	0xe3, 0xb6, 0xb1, 0xec, 0x2c, 0x3b, 0x83, 0xd2, 0x18, 0x2f, 0x1e, 0x3c, 0x9b, 0xf0, 0xb7, 0x68,
	0x22, 0x26, 0x9c, 0x39, 0x92, 0x78, 0xf1, 0x64, 0x0c, 0xf5, 0x0f, 0x31, 0x9d, 0x9d, 0xd2, 0x99,
	0x74, 0x77, 0x3b, 0xa5, 0xf5, 0xd6, 0xdd, 0x7d, 0xef, 0xf3, 0x3e, 0x9f, 0xcf, 0x9b, 0xbe, 0x37,
	0xf0, 0x26, 0x6d, 0xbc, 0x23, 0x65, 0x16, 0x88, 0x88, 0x94, 0x85, 0x67, 0x3c, 0xec, 0xec, 0xd2,
	0xa8, 0xe1, 0x86, 0x11, 0x13, 0x0c, 0x5d, 0xd2, 0xbf, 0xb8, 0xfa, 0x43, 0x7e, 0xda, 0x67, 0x3e,
	0x93, 0x51, 0x5e, 0xeb, 0x57, 0x9c, 0x90, 0x9f, 0xf1, 0x19, 0xf3, 0xeb, 0xd4, 0x23, 0x61, 0xcd,
	0x23, 0x41, 0xc0, 0x04, 0x11, 0x35, 0x16, 0x70, 0xf5, 0x75, 0xbe, 0xcc, 0xf8, 0x36, 0xe3, 0xde,
	0x16, 0xe1, 0x34, 0xae, 0xe3, 0xbd, 0x2d, 0x6c, 0x51, 0x41, 0x0a, 0x5e, 0x48, 0xfc, 0x5a, 0x20,
	0x83, 0x55, 0xec, 0x6c, 0x3a, 0xc3, 0x90, 0x44, 0x64, 0xbb, 0x8d, 0xb9, 0x90, 0x1e, 0x17, 0x51,
	0xbf, 0xc6, 0x05, 0x8d, 0x36, 0x45, 0x23, 0xa4, 0x2a, 0xdc, 0x4d, 0x0f, 0xe7, 0x34, 0xa8, 0x6c,
	0x96, 0xab, 0x44, 0x58, 0xc6, 0x57, 0x49, 0x50, 0xe1, 0x55, 0xf2, 0x86, 0x6a, 0xf1, 0x78, 0x1a,
	0xa2, 0xf5, 0x96, 0xb0, 0x35, 0xc9, 0xb1, 0x44, 0x77, 0x76, 0x29, 0x17, 0xf8, 0x25, 0xbc, 0x60,
	0xbc, 0xe5, 0x21, 0x0b, 0x38, 0x45, 0x4f, 0xe0, 0x78, 0xac, 0xe5, 0x22, 0xb8, 0x06, 0xe6, 0xce,
	0x15, 0xaf, 0xbb, 0xa9, 0x7e, 0xbb, 0x71, 0xea, 0xca, 0x7f, 0x47, 0xbf, 0xae, 0xe6, 0x4a, 0x2a,
	0x0d, 0x2f, 0xc2, 0xcb, 0x12, 0x77, 0x95, 0x8a, 0x92, 0x12, 0xbb, 0xd1, 0x08, 0xa9, 0x2a, 0x8b,
	0xa6, 0xe1, 0x58, 0x2d, 0xa8, 0xd0, 0x3d, 0x09, 0xff, 0x7f, 0x29, 0x7e, 0xc0, 0x3b, 0x70, 0x26,
	0x39, 0x49, 0xb1, 0x5a, 0x87, 0x13, 0x91, 0xf6, 0x5e, 0x71, 0xbb, 0x95, 0xc1, 0x4d, 0x87, 0x51,
	0x0c, 0x0d, 0x08, 0x4c, 0x15, 0xcf, 0xe5, 0x7a, 0x3d, 0x89, 0xe7, 0x33, 0x08, 0x3b, 0xfd, 0x57,
	0xf5, 0x66, 0xdd, 0xf8, 0xb0, 0xb8, 0xad, 0xc3, 0xe2, 0xc6, 0x87, 0x52, 0x1d, 0x16, 0x77, 0x8d,
	0xf8, 0xed, 0xdc, 0x92, 0x96, 0x89, 0x0f, 0x80, 0x92, 0xd6, 0x55, 0x27, 0x55, 0xda, 0xe8, 0x80,
	0xd2, 0xd0, 0xaa, 0xc1, 0x7d, 0x44, 0x79, 0xd5, 0x8b, 0x7b, 0xcc, 0xc7, 0x20, 0xaf, 0xf5, 0xf2,
	0x05, 0x0d, 0x2a, 0x4f, 0xab, 0x44, 0xf4, 0xd5, 0x4b, 0x33, 0xa9, 0x23, 0x98, 0x6b, 0xef, 0x2d,
	0x7a, 0xa9, 0xc3, 0xb4, 0x05, 0xeb, 0x10, 0x7a, 0x2f, 0x93, 0x78, 0xfe, 0x8b, 0x5e, 0x5a, 0x4a,
	0x1b, 0x1d, 0x50, 0xda, 0xf0, 0x7a, 0xb9, 0xd4, 0x69, 0xcb, 0xf3, 0xf6, 0x94, 0xe8, 0xdd, 0xcc,
	0x5d, 0x78, 0x25, 0x25, 0x4b, 0x49, 0xde, 0x80, 0x93, 0x55, 0xfd, 0x83, 0xb2, 0x77, 0x2e, 0x43,
	0xb3, 0x01, 0xa4, 0x44, 0x9b, 0x20, 0xf8, 0x75, 0xc7, 0xe8, 0x44, 0xb2, 0xc3, 0xea, 0xe8, 0x21,
	0x50, 0xfa, 0xba, 0x0b, 0xa5, 0xeb, 0x1b, 0x1d, 0x58, 0xdf, 0xd0, 0xba, 0x5a, 0xfc, 0x04, 0xe1,
	0x98, 0x14, 0x80, 0xf6, 0x01, 0x1c, 0x8f, 0x07, 0x32, 0x5a, 0xc8, 0x20, 0xd7, 0xbd, 0x09, 0xf2,
	0xae, 0x6d, 0x78, 0x5c, 0x1f, 0xcf, 0x7f, 0xfc, 0xf1, 0x67, 0x7f, 0xe4, 0x06, 0xc2, 0x72, 0xf7,
	0x2c, 0x64, 0x2d, 0x44, 0x74, 0x00, 0xe0, 0x84, 0x3e, 0xaf, 0xd0, 0xbd, 0x5e, 0xc5, 0x92, 0xf7,
	0x46, 0xfe, 0x7e, 0xdf, 0x79, 0x8a, 0xed, 0x43, 0xc9, 0x76, 0x11, 0x15, 0xb2, 0xd8, 0x1a, 0x6b,
	0xd9, 0x7b, 0x2f, 0xcf, 0xfe, 0x07, 0xf4, 0x05, 0xc0, 0x29, 0x1d, 0x73, 0xb9, 0x5e, 0xef, 0xcd,
	0x3f, 0x79, 0x9f, 0xf4, 0xe6, 0x9f, 0xb2, 0x1f, 0x70, 0x41, 0xf2, 0xbf, 0x83, 0x6e, 0x5b, 0xf3,
	0x47, 0xdf, 0x01, 0x9c, 0xd0, 0x07, 0x8b, 0x95, 0xe9, 0x09, 0x83, 0xd3, 0xca, 0xf4, 0xa4, 0x41,
	0x88, 0x1f, 0x49, 0xd2, 0x4b, 0xa8, 0x98, 0x45, 0xda, 0xbc, 0xdc, 0x9c, 0xba, 0xfe, 0x15, 0xc0,
	0x29, 0x1d, 0xd4, 0xd6, 0xf5, 0x33, 0x09, 0x48, 0x99, 0xe4, 0xb8, 0x28, 0x05, 0xdc, 0x45, 0xf3,
	0xf6, 0x02, 0xd0, 0x21, 0x80, 0x93, 0xc6, 0x7f, 0x1f, 0xd9, 0xf8, 0x97, 0x34, 0xdf, 0xf2, 0x0f,
	0xfa, 0x4f, 0xec, 0xc7, 0x79, 0xf3, 0x9a, 0x78, 0xea, 0xfc, 0x37, 0x00, 0xcf, 0x1b, 0xa8, 0x2d,
	0xeb, 0x6d, 0x2c, 0x3c, 0x9b, 0x86, 0xb4, 0x99, 0x6b, 0x67, 0xbe, 0xa9, 0x61, 0xe5, 0xf1, 0xd1,
	0x89, 0x03, 0x8e, 0x4f, 0x1c, 0xf0, 0xfb, 0xc4, 0x01, 0x9f, 0x9b, 0x4e, 0xee, 0xb8, 0xe9, 0xe4,
	0x7e, 0x36, 0x9d, 0xdc, 0x2b, 0x6c, 0x82, 0xec, 0x99, 0x30, 0xad, 0x64, 0xbe, 0x35, 0x2e, 0x6f,
	0xca, 0x8b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x01, 0x68, 0x59, 0xf5, 0x84, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of RegisterType items.
	RegisterType(ctx context.Context, in *QueryGetRegisterTypeRequest, opts ...grpc.CallOption) (*QueryGetRegisterTypeResponse, error)
	RegisterTypeAll(ctx context.Context, in *QueryAllRegisterTypeRequest, opts ...grpc.CallOption) (*QueryAllRegisterTypeResponse, error)
	// Queries a list of SendChatType items.
	SendChatType(ctx context.Context, in *QueryGetSendChatTypeRequest, opts ...grpc.CallOption) (*QueryGetSendChatTypeResponse, error)
	SendChatTypeAll(ctx context.Context, in *QueryAllSendChatTypeRequest, opts ...grpc.CallOption) (*QueryAllSendChatTypeResponse, error)
	// Queries a list of HandshakeType items.
	HandshakeType(ctx context.Context, in *QueryGetHandshakeTypeRequest, opts ...grpc.CallOption) (*QueryGetHandshakeTypeResponse, error)
	HandshakeTypeAll(ctx context.Context, in *QueryAllHandshakeTypeRequest, opts ...grpc.CallOption) (*QueryAllHandshakeTypeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/eywacontract.eywacontract.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegisterType(ctx context.Context, in *QueryGetRegisterTypeRequest, opts ...grpc.CallOption) (*QueryGetRegisterTypeResponse, error) {
	out := new(QueryGetRegisterTypeResponse)
	err := c.cc.Invoke(ctx, "/eywacontract.eywacontract.Query/RegisterType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegisterTypeAll(ctx context.Context, in *QueryAllRegisterTypeRequest, opts ...grpc.CallOption) (*QueryAllRegisterTypeResponse, error) {
	out := new(QueryAllRegisterTypeResponse)
	err := c.cc.Invoke(ctx, "/eywacontract.eywacontract.Query/RegisterTypeAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SendChatType(ctx context.Context, in *QueryGetSendChatTypeRequest, opts ...grpc.CallOption) (*QueryGetSendChatTypeResponse, error) {
	out := new(QueryGetSendChatTypeResponse)
	err := c.cc.Invoke(ctx, "/eywacontract.eywacontract.Query/SendChatType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SendChatTypeAll(ctx context.Context, in *QueryAllSendChatTypeRequest, opts ...grpc.CallOption) (*QueryAllSendChatTypeResponse, error) {
	out := new(QueryAllSendChatTypeResponse)
	err := c.cc.Invoke(ctx, "/eywacontract.eywacontract.Query/SendChatTypeAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) HandshakeType(ctx context.Context, in *QueryGetHandshakeTypeRequest, opts ...grpc.CallOption) (*QueryGetHandshakeTypeResponse, error) {
	out := new(QueryGetHandshakeTypeResponse)
	err := c.cc.Invoke(ctx, "/eywacontract.eywacontract.Query/HandshakeType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) HandshakeTypeAll(ctx context.Context, in *QueryAllHandshakeTypeRequest, opts ...grpc.CallOption) (*QueryAllHandshakeTypeResponse, error) {
	out := new(QueryAllHandshakeTypeResponse)
	err := c.cc.Invoke(ctx, "/eywacontract.eywacontract.Query/HandshakeTypeAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of RegisterType items.
	RegisterType(context.Context, *QueryGetRegisterTypeRequest) (*QueryGetRegisterTypeResponse, error)
	RegisterTypeAll(context.Context, *QueryAllRegisterTypeRequest) (*QueryAllRegisterTypeResponse, error)
	// Queries a list of SendChatType items.
	SendChatType(context.Context, *QueryGetSendChatTypeRequest) (*QueryGetSendChatTypeResponse, error)
	SendChatTypeAll(context.Context, *QueryAllSendChatTypeRequest) (*QueryAllSendChatTypeResponse, error)
	// Queries a list of HandshakeType items.
	HandshakeType(context.Context, *QueryGetHandshakeTypeRequest) (*QueryGetHandshakeTypeResponse, error)
	HandshakeTypeAll(context.Context, *QueryAllHandshakeTypeRequest) (*QueryAllHandshakeTypeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) RegisterType(ctx context.Context, req *QueryGetRegisterTypeRequest) (*QueryGetRegisterTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterType not implemented")
}
func (*UnimplementedQueryServer) RegisterTypeAll(ctx context.Context, req *QueryAllRegisterTypeRequest) (*QueryAllRegisterTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTypeAll not implemented")
}
func (*UnimplementedQueryServer) SendChatType(ctx context.Context, req *QueryGetSendChatTypeRequest) (*QueryGetSendChatTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendChatType not implemented")
}
func (*UnimplementedQueryServer) SendChatTypeAll(ctx context.Context, req *QueryAllSendChatTypeRequest) (*QueryAllSendChatTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendChatTypeAll not implemented")
}
func (*UnimplementedQueryServer) HandshakeType(ctx context.Context, req *QueryGetHandshakeTypeRequest) (*QueryGetHandshakeTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandshakeType not implemented")
}
func (*UnimplementedQueryServer) HandshakeTypeAll(ctx context.Context, req *QueryAllHandshakeTypeRequest) (*QueryAllHandshakeTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandshakeTypeAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eywacontract.eywacontract.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegisterType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRegisterTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegisterType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eywacontract.eywacontract.Query/RegisterType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegisterType(ctx, req.(*QueryGetRegisterTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegisterTypeAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRegisterTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegisterTypeAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eywacontract.eywacontract.Query/RegisterTypeAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegisterTypeAll(ctx, req.(*QueryAllRegisterTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SendChatType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSendChatTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SendChatType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eywacontract.eywacontract.Query/SendChatType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SendChatType(ctx, req.(*QueryGetSendChatTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SendChatTypeAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSendChatTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SendChatTypeAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eywacontract.eywacontract.Query/SendChatTypeAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SendChatTypeAll(ctx, req.(*QueryAllSendChatTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_HandshakeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetHandshakeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).HandshakeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eywacontract.eywacontract.Query/HandshakeType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).HandshakeType(ctx, req.(*QueryGetHandshakeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_HandshakeTypeAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllHandshakeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).HandshakeTypeAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eywacontract.eywacontract.Query/HandshakeTypeAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).HandshakeTypeAll(ctx, req.(*QueryAllHandshakeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eywacontract.eywacontract.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "RegisterType",
			Handler:    _Query_RegisterType_Handler,
		},
		{
			MethodName: "RegisterTypeAll",
			Handler:    _Query_RegisterTypeAll_Handler,
		},
		{
			MethodName: "SendChatType",
			Handler:    _Query_SendChatType_Handler,
		},
		{
			MethodName: "SendChatTypeAll",
			Handler:    _Query_SendChatTypeAll_Handler,
		},
		{
			MethodName: "HandshakeType",
			Handler:    _Query_HandshakeType_Handler,
		},
		{
			MethodName: "HandshakeTypeAll",
			Handler:    _Query_HandshakeTypeAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eywacontract/eywacontract/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetRegisterTypeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRegisterTypeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRegisterTypeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRegisterTypeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRegisterTypeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRegisterTypeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RegisterType.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllRegisterTypeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRegisterTypeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRegisterTypeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRegisterTypeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRegisterTypeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRegisterTypeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.RegisterType) > 0 {
		for iNdEx := len(m.RegisterType) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RegisterType[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSendChatTypeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSendChatTypeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSendChatTypeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSendChatTypeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSendChatTypeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSendChatTypeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SendChatType.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllSendChatTypeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSendChatTypeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSendChatTypeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSendChatTypeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSendChatTypeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSendChatTypeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.SendChatType) > 0 {
		for iNdEx := len(m.SendChatType) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SendChatType[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetHandshakeTypeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetHandshakeTypeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetHandshakeTypeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetHandshakeTypeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetHandshakeTypeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetHandshakeTypeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.HandshakeType.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllHandshakeTypeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllHandshakeTypeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllHandshakeTypeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllHandshakeTypeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllHandshakeTypeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllHandshakeTypeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.HandshakeType) > 0 {
		for iNdEx := len(m.HandshakeType) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HandshakeType[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetRegisterTypeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRegisterTypeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.RegisterType.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllRegisterTypeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRegisterTypeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RegisterType) > 0 {
		for _, e := range m.RegisterType {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSendChatTypeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSendChatTypeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SendChatType.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllSendChatTypeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSendChatTypeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SendChatType) > 0 {
		for _, e := range m.SendChatType {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetHandshakeTypeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetHandshakeTypeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.HandshakeType.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllHandshakeTypeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllHandshakeTypeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.HandshakeType) > 0 {
		for _, e := range m.HandshakeType {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRegisterTypeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRegisterTypeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRegisterTypeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRegisterTypeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRegisterTypeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRegisterTypeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RegisterType.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRegisterTypeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRegisterTypeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRegisterTypeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRegisterTypeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRegisterTypeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRegisterTypeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegisterType = append(m.RegisterType, RegisterType{})
			if err := m.RegisterType[len(m.RegisterType)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSendChatTypeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSendChatTypeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSendChatTypeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSendChatTypeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSendChatTypeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSendChatTypeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendChatType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SendChatType.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSendChatTypeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSendChatTypeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSendChatTypeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSendChatTypeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSendChatTypeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSendChatTypeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendChatType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SendChatType = append(m.SendChatType, SendChatType{})
			if err := m.SendChatType[len(m.SendChatType)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetHandshakeTypeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetHandshakeTypeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetHandshakeTypeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetHandshakeTypeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetHandshakeTypeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetHandshakeTypeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HandshakeType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.HandshakeType.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllHandshakeTypeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllHandshakeTypeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllHandshakeTypeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllHandshakeTypeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllHandshakeTypeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllHandshakeTypeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HandshakeType", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HandshakeType = append(m.HandshakeType, HandshakeType{})
			if err := m.HandshakeType[len(m.HandshakeType)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
