// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgRegister } from "./types/eywacontract/eywacontract/tx";
import { MsgHandshake } from "./types/eywacontract/eywacontract/tx";
import { MsgSendChat } from "./types/eywacontract/eywacontract/tx";

import { HandshakeType as typeHandshakeType} from "./types"
import { Params as typeParams} from "./types"
import { RegisterType as typeRegisterType} from "./types"
import { SendChatType as typeSendChatType} from "./types"

export { MsgRegister, MsgHandshake, MsgSendChat };

type sendMsgRegisterParams = {
  value: MsgRegister,
  fee?: StdFee,
  memo?: string
};

type sendMsgHandshakeParams = {
  value: MsgHandshake,
  fee?: StdFee,
  memo?: string
};

type sendMsgSendChatParams = {
  value: MsgSendChat,
  fee?: StdFee,
  memo?: string
};


type msgRegisterParams = {
  value: MsgRegister,
};

type msgHandshakeParams = {
  value: MsgHandshake,
};

type msgSendChatParams = {
  value: MsgSendChat,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgRegister({ value, fee, memo }: sendMsgRegisterParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRegister: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRegister({ value: MsgRegister.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRegister: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgHandshake({ value, fee, memo }: sendMsgHandshakeParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgHandshake: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgHandshake({ value: MsgHandshake.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgHandshake: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSendChat({ value, fee, memo }: sendMsgSendChatParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSendChat: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendChat({ value: MsgSendChat.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSendChat: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgRegister({ value }: msgRegisterParams): EncodeObject {
			try {
				return { typeUrl: "/eywacontract.eywacontract.MsgRegister", value: MsgRegister.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRegister: Could not create message: ' + e.message)
			}
		},
		
		msgHandshake({ value }: msgHandshakeParams): EncodeObject {
			try {
				return { typeUrl: "/eywacontract.eywacontract.MsgHandshake", value: MsgHandshake.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgHandshake: Could not create message: ' + e.message)
			}
		},
		
		msgSendChat({ value }: msgSendChatParams): EncodeObject {
			try {
				return { typeUrl: "/eywacontract.eywacontract.MsgSendChat", value: MsgSendChat.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSendChat: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						HandshakeType: getStructure(typeHandshakeType.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						RegisterType: getStructure(typeRegisterType.fromPartial({})),
						SendChatType: getStructure(typeSendChatType.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			EywacontractEywacontract: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;